FROM node:13.6.0-stretch

RUN curl https://install.meteor.com/ | sh
#RUN meteor npm install --save react react-dom --allow-superuser
#RUN meteor remove blaze-html-templates --allow-superuser
#RUN meteor add static-html --allow-superuser

WORKDIR /app